apiVersion: v1
kind: Namespace
metadata:
  name: storageos-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-cluster-operator
  namespace: storageos-operator
spec:
  selector:
    matchLabels:
      name: storageos-cluster-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: storageos-cluster-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: storageos/cluster-operator:test
        name: storageos-cluster-operator
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
