
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: storageos-operator-role
rules:
- apiGroups:
  - storageos.com
  resources:
  - storageosclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storageos.com
  resources:
  - storageosclusters/status
  verbs:
  - get
  - patch
  - update
