apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-cluster-operator
  namespace: storageos-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: storageos-cluster-operator
  template:
    metadata:
      labels:
        name: storageos-cluster-operator
    spec:
      serviceAccountName: storageoscluster-operator-sa
      containers:
        - name: storageos-cluster-operator
          image: storageos/cluster-operator:test
          ports:
          - containerPort: 60000
            name: metrics
          - containerPort: 5720
            name: podschedwebhook
          command:
          - cluster-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "cluster-operator"
            - name: DISABLE_SCHEDULER_WEBHOOK
              value: "false"
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule" 
